import cv2
import imutils
from imutils.video import VideoStream
from ccapi.ccapi import CCAPI

camera = CCAPI(ip="192.168.50.210")
# replace this with the url generated by the Wyze app

camera.cam_start()

rtsp_url = "rtsp://192.168.50.211:8081/ccapi/ver100/shooting/liveview/rtp"

vs = VideoStream(rtsp_url).start()

print ("LLLL")
while True:
    frame = vs.read()

    if frame is None:
        continue

    frame = imutils.resize(frame, width=1200)
    print(frame)

    cv2.imshow('WyzeCam', frame)

    key = cv2.waitKey(1) & 0xFF

    if key == ord('q'):
        break

cv2.destroyAllWindows()
vs.stop()
camera.cam_stop()